
package com.jeecms.wdedu.outsides;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserWebServieImplService", targetNamespace = "http://webservices.cms.jeecms.com/", wsdlLocation = "http://106.15.89.230:9095/webservice/WebServicePublish?wsdl")
public class UserWebServieImplService
    extends Service
{

    private final static URL USERWEBSERVIEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERWEBSERVIEIMPLSERVICE_EXCEPTION;
    private final static QName USERWEBSERVIEIMPLSERVICE_QNAME = new QName("http://webservices.cms.jeecms.com/", "UserWebServieImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://106.15.89.230:9095/webservice/WebServicePublish?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERWEBSERVIEIMPLSERVICE_WSDL_LOCATION = url;
        USERWEBSERVIEIMPLSERVICE_EXCEPTION = e;
    }

    public UserWebServieImplService() {
        super(__getWsdlLocation(), USERWEBSERVIEIMPLSERVICE_QNAME);
    }

    public UserWebServieImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERWEBSERVIEIMPLSERVICE_QNAME, features);
    }

    public UserWebServieImplService(URL wsdlLocation) {
        super(wsdlLocation, USERWEBSERVIEIMPLSERVICE_QNAME);
    }

    public UserWebServieImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERWEBSERVIEIMPLSERVICE_QNAME, features);
    }

    public UserWebServieImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserWebServieImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserWebServieImpl
     */
    @WebEndpoint(name = "UserWebServieImplPort")
    public UserWebServieImpl getUserWebServieImplPort() {
        return super.getPort(new QName("http://webservices.cms.jeecms.com/", "UserWebServieImplPort"), UserWebServieImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserWebServieImpl
     */
    @WebEndpoint(name = "UserWebServieImplPort")
    public UserWebServieImpl getUserWebServieImplPort(WebServiceFeature... features) {

        return super.getPort(new QName("http://webservices.cms.jeecms.com/", "UserWebServieImplPort"), UserWebServieImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERWEBSERVIEIMPLSERVICE_EXCEPTION!= null) {
            throw USERWEBSERVIEIMPLSERVICE_EXCEPTION;
        }
        return USERWEBSERVIEIMPLSERVICE_WSDL_LOCATION;
    }

}
